O_TARGET=liblguicore.o
obj-y=blockheap.o caret.o clipregion.o initgui.o invalidregion.o \
	ipc.o keyboard_pro.o gmessage.o mouse.o rect.o regclass.o \
	shmem.o stack.o system.o skbwin.o \
	text.o winnc.o winbase.o window.o keyboard.o port.o gtimer.o
include $(TOPDIR)/rule.mk
