O_TARGET:= gui.o
obj-y=control/libcontrol.o lguicore/liblguicore.o gal/libgal.o gdi/libgdi.o\
	hdc/libhdc.o ial/libial.o ime/libime.o src/src.o lib/lib.o 
subdir-y=src control lguicore gal gdi hdc ial ime lib
include $(TOPDIR)/rule.mk
