/*
 * Automatically generated by config: don't edit
 */
#ifndef AUTOCONF_H
#define AUTOCONF_H
#define CFG_X86_EMU_CMP
#define CFG_GUI_EMU
#define CFG_CMP
#define CFG_MAX_CPU 2
#define CFG_MEM_BUDDY
#define CFG_MAX_THREAD 10
#define CFG_MIN_STACK_SIZE 2048
#define CFG_TICKS_PER_SEC 100
#define CFG_DRIVER
#define CFG_DRV_CONSOLE
#define CFG_DRV_EMU_DISK
#define CFG_LIB_EXT
#define CFG_SHELL
#define CFG_UART_SHELL
#define CFG_BAUD_RATE 115200
#define __GNU_C__
#endif
